/**
 * @file sim_visualization.c
 * @brief Visualization and reporting for simulation results
 * 
 * Generates gnuplot scripts for time-series plots, BER vs SNR curves,
 * and constellation diagrams.
 */

#include "simulator.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

/* ============================================================================
 * Gnuplot Script Generation
 * ============================================================================ */

/**
 * @brief Generate gnuplot script for time-series plots
 * 
 * Creates a gnuplot script to visualize BER, SNR, and throughput over time.
 * 
 * @param csv_filename Input CSV file with time-series data
 * @param output_filename Output image filename (PNG)
 * @param script_filename Output gnuplot script filename
 * @return FSO_SUCCESS on success, error code otherwise
 * 
 * @note Requirement 6.5: Generate gnuplot scripts for time-series plots
 */
int sim_generate_timeseries_plot(const char* csv_filename,
                                 const char* output_filename,
                                 const char* script_filename) {
    if (csv_filename == NULL || output_filename == NULL || script_filename == NULL) {
        FSO_LOG_ERROR("Visualization", "NULL pointer in generate_timeseries_plot");
        return FSO_ERROR_INVALID_PARAM;
    }
    
    FILE* fp = fopen(script_filename, "w");
    if (fp == NULL) {
        FSO_LOG_ERROR("Visualization", "Failed to create gnuplot script: %s", script_filename);
        return FSO_ERROR_IO;
    }
    
    fprintf(fp, "# Gnuplot script for time-series visualization\n");
    fprintf(fp, "# Generated by FSO Communication Suite\n\n");
    
    fprintf(fp, "set terminal png size 1200,800 enhanced font 'Arial,10'\n");
    fprintf(fp, "set output '%s'\n\n", output_filename);
    
    fprintf(fp, "set multiplot layout 3,1 title 'FSO Link Performance Over Time'\n\n");
    
    // Plot 1: BER over time
    fprintf(fp, "# Plot 1: Bit Error Rate\n");
    fprintf(fp, "set xlabel 'Time (s)'\n");
    fprintf(fp, "set ylabel 'BER'\n");
    fprintf(fp, "set logscale y\n");
    fprintf(fp, "set grid\n");
    fprintf(fp, "set key top right\n");
    fprintf(fp, "plot '%s' using 1:2 with lines lw 2 title 'BER'\n\n", csv_filename);
    
    // Plot 2: SNR over time
    fprintf(fp, "# Plot 2: Signal-to-Noise Ratio\n");
    fprintf(fp, "set xlabel 'Time (s)'\n");
    fprintf(fp, "set ylabel 'SNR (dB)'\n");
    fprintf(fp, "unset logscale y\n");
    fprintf(fp, "set grid\n");
    fprintf(fp, "plot '%s' using 1:3 with lines lw 2 lc rgb 'blue' title 'SNR'\n\n", csv_filename);
    
    // Plot 3: Throughput over time
    fprintf(fp, "# Plot 3: Throughput\n");
    fprintf(fp, "set xlabel 'Time (s)'\n");
    fprintf(fp, "set ylabel 'Throughput (bits/s)'\n");
    fprintf(fp, "set grid\n");
    fprintf(fp, "plot '%s' using 1:5 with lines lw 2 lc rgb 'green' title 'Throughput'\n\n", csv_filename);
    
    fprintf(fp, "unset multiplot\n");
    
    fclose(fp);
    
    FSO_LOG_INFO("Visualization", "Generated time-series plot script: %s", script_filename);
    return FSO_SUCCESS;
}

/**
 * @brief Generate gnuplot script for BER vs SNR curve
 * 
 * Creates a gnuplot script to plot BER as a function of SNR.
 * 
 * @param csv_filename Input CSV file with packet statistics
 * @param output_filename Output image filename (PNG)
 * @param script_filename Output gnuplot script filename
 * @return FSO_SUCCESS on success, error code otherwise
 * 
 * @note Requirement 6.5: Create BER vs SNR curve plotting
 */
int sim_generate_ber_snr_plot(const char* csv_filename,
                              const char* output_filename,
                              const char* script_filename) {
    if (csv_filename == NULL || output_filename == NULL || script_filename == NULL) {
        FSO_LOG_ERROR("Visualization", "NULL pointer in generate_ber_snr_plot");
        return FSO_ERROR_INVALID_PARAM;
    }
    
    FILE* fp = fopen(script_filename, "w");
    if (fp == NULL) {
        FSO_LOG_ERROR("Visualization", "Failed to create gnuplot script: %s", script_filename);
        return FSO_ERROR_IO;
    }
    
    fprintf(fp, "# Gnuplot script for BER vs SNR curve\n");
    fprintf(fp, "# Generated by FSO Communication Suite\n\n");
    
    fprintf(fp, "set terminal png size 800,600 enhanced font 'Arial,10'\n");
    fprintf(fp, "set output '%s'\n\n", output_filename);
    
    fprintf(fp, "set title 'Bit Error Rate vs Signal-to-Noise Ratio'\n");
    fprintf(fp, "set xlabel 'SNR (dB)'\n");
    fprintf(fp, "set ylabel 'BER'\n");
    fprintf(fp, "set logscale y\n");
    fprintf(fp, "set grid\n");
    fprintf(fp, "set key top right\n\n");
    
    fprintf(fp, "# Plot measured BER vs SNR\n");
    fprintf(fp, "plot '%s' using 6:5 with points pt 7 ps 0.5 lc rgb 'red' title 'Measured BER'\n", 
            csv_filename);
    
    fclose(fp);
    
    FSO_LOG_INFO("Visualization", "Generated BER vs SNR plot script: %s", script_filename);
    return FSO_SUCCESS;
}

/**
 * @brief Generate gnuplot script for constellation diagram
 * 
 * Creates a gnuplot script to visualize modulation constellation.
 * Note: This requires complex symbol data which would need to be exported separately.
 * 
 * @param data_filename Input data file with I/Q samples
 * @param output_filename Output image filename (PNG)
 * @param script_filename Output gnuplot script filename
 * @param modulation Modulation type
 * @return FSO_SUCCESS on success, error code otherwise
 * 
 * @note Requirement 6.5: Add constellation diagram generation
 */
int sim_generate_constellation_plot(const char* data_filename,
                                    const char* output_filename,
                                    const char* script_filename,
                                    ModulationType modulation) {
    if (data_filename == NULL || output_filename == NULL || script_filename == NULL) {
        FSO_LOG_ERROR("Visualization", "NULL pointer in generate_constellation_plot");
        return FSO_ERROR_INVALID_PARAM;
    }
    
    FILE* fp = fopen(script_filename, "w");
    if (fp == NULL) {
        FSO_LOG_ERROR("Visualization", "Failed to create gnuplot script: %s", script_filename);
        return FSO_ERROR_IO;
    }
    
    fprintf(fp, "# Gnuplot script for constellation diagram\n");
    fprintf(fp, "# Generated by FSO Communication Suite\n\n");
    
    fprintf(fp, "set terminal png size 600,600 enhanced font 'Arial,10'\n");
    fprintf(fp, "set output '%s'\n\n", output_filename);
    
    const char* mod_name = sim_modulation_string(modulation);
    fprintf(fp, "set title '%s Constellation Diagram'\n", mod_name);
    fprintf(fp, "set xlabel 'In-Phase'\n");
    fprintf(fp, "set ylabel 'Quadrature'\n");
    fprintf(fp, "set size square\n");
    fprintf(fp, "set grid\n");
    fprintf(fp, "unset key\n\n");
    
    fprintf(fp, "# Plot constellation points\n");
    fprintf(fp, "plot '%s' using 1:2 with points pt 7 ps 0.3 lc rgb 'blue'\n", data_filename);
    
    fclose(fp);
    
    FSO_LOG_INFO("Visualization", "Generated constellation plot script: %s", script_filename);
    return FSO_SUCCESS;
}

/**
 * @brief Generate gnuplot script for beam tracking visualization
 * 
 * Creates a gnuplot script to visualize beam position over time.
 * 
 * @param csv_filename Input CSV file with time-series data including beam position
 * @param output_filename Output image filename (PNG)
 * @param script_filename Output gnuplot script filename
 * @return FSO_SUCCESS on success, error code otherwise
 */
int sim_generate_tracking_plot(const char* csv_filename,
                               const char* output_filename,
                               const char* script_filename) {
    if (csv_filename == NULL || output_filename == NULL || script_filename == NULL) {
        FSO_LOG_ERROR("Visualization", "NULL pointer in generate_tracking_plot");
        return FSO_ERROR_INVALID_PARAM;
    }
    
    FILE* fp = fopen(script_filename, "w");
    if (fp == NULL) {
        FSO_LOG_ERROR("Visualization", "Failed to create gnuplot script: %s", script_filename);
        return FSO_ERROR_IO;
    }
    
    fprintf(fp, "# Gnuplot script for beam tracking visualization\n");
    fprintf(fp, "# Generated by FSO Communication Suite\n\n");
    
    fprintf(fp, "set terminal png size 1200,600 enhanced font 'Arial,10'\n");
    fprintf(fp, "set output '%s'\n\n", output_filename);
    
    fprintf(fp, "set multiplot layout 1,2 title 'Beam Tracking Performance'\n\n");
    
    // Plot 1: Beam position over time
    fprintf(fp, "# Plot 1: Beam Position\n");
    fprintf(fp, "set xlabel 'Time (s)'\n");
    fprintf(fp, "set ylabel 'Angle (rad)'\n");
    fprintf(fp, "set grid\n");
    fprintf(fp, "set key top right\n");
    fprintf(fp, "plot '%s' using 1:6 with lines lw 2 lc rgb 'red' title 'Azimuth', \\\n", 
            csv_filename);
    fprintf(fp, "     '%s' using 1:7 with lines lw 2 lc rgb 'blue' title 'Elevation'\n\n",
            csv_filename);
    
    // Plot 2: Signal strength over time
    fprintf(fp, "# Plot 2: Signal Strength\n");
    fprintf(fp, "set xlabel 'Time (s)'\n");
    fprintf(fp, "set ylabel 'Signal Strength'\n");
    fprintf(fp, "set grid\n");
    fprintf(fp, "plot '%s' using 1:8 with lines lw 2 lc rgb 'green' title 'Signal Strength'\n\n",
            csv_filename);
    
    fprintf(fp, "unset multiplot\n");
    
    fclose(fp);
    
    FSO_LOG_INFO("Visualization", "Generated tracking plot script: %s", script_filename);
    return FSO_SUCCESS;
}

/* ============================================================================
 * Comprehensive Report Generation
 * ============================================================================ */

/**
 * @brief Generate comprehensive HTML report
 * 
 * Creates an HTML report with simulation results, plots, and analysis.
 * 
 * @param config Simulation configuration
 * @param results Simulation results
 * @param output_filename Output HTML filename
 * @return FSO_SUCCESS on success, error code otherwise
 */
int sim_generate_html_report(const SimConfig* config,
                             const SimResults* results,
                             const char* output_filename) {
    if (config == NULL || results == NULL || output_filename == NULL) {
        FSO_LOG_ERROR("Visualization", "NULL pointer in generate_html_report");
        return FSO_ERROR_INVALID_PARAM;
    }
    
    FILE* fp = fopen(output_filename, "w");
    if (fp == NULL) {
        FSO_LOG_ERROR("Visualization", "Failed to create HTML report: %s", output_filename);
        return FSO_ERROR_IO;
    }
    
    // HTML header
    fprintf(fp, "<!DOCTYPE html>\n");
    fprintf(fp, "<html>\n<head>\n");
    fprintf(fp, "<title>FSO Simulation Report</title>\n");
    fprintf(fp, "<style>\n");
    fprintf(fp, "body { font-family: Arial, sans-serif; margin: 20px; }\n");
    fprintf(fp, "h1 { color: #333; }\n");
    fprintf(fp, "h2 { color: #666; border-bottom: 2px solid #ccc; padding-bottom: 5px; }\n");
    fprintf(fp, "table { border-collapse: collapse; margin: 20px 0; }\n");
    fprintf(fp, "th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }\n");
    fprintf(fp, "th { background-color: #f2f2f2; }\n");
    fprintf(fp, ".metric { font-weight: bold; color: #0066cc; }\n");
    fprintf(fp, "</style>\n");
    fprintf(fp, "</head>\n<body>\n\n");
    
    // Title
    fprintf(fp, "<h1>FSO Communication Link Simulation Report</h1>\n");
    fprintf(fp, "<p>Generated by FSO Communication Protocol Suite</p>\n\n");
    
    // Configuration section
    fprintf(fp, "<h2>Configuration</h2>\n");
    fprintf(fp, "<table>\n");
    fprintf(fp, "<tr><th>Parameter</th><th>Value</th></tr>\n");
    fprintf(fp, "<tr><td>Link Distance</td><td>%.1f m</td></tr>\n", 
            config->link.link_distance);
    fprintf(fp, "<tr><td>Transmit Power</td><td>%.3e W (%.2f dBm)</td></tr>\n",
            config->link.transmit_power, fso_watts_to_dbm(config->link.transmit_power));
    fprintf(fp, "<tr><td>Wavelength</td><td>%.1f nm</td></tr>\n",
            config->link.wavelength * 1e9);
    fprintf(fp, "<tr><td>Weather</td><td>%s</td></tr>\n",
            sim_weather_string(config->environment.weather));
    fprintf(fp, "<tr><td>Modulation</td><td>%s</td></tr>\n",
            sim_modulation_string(config->system.modulation));
    fprintf(fp, "<tr><td>FEC</td><td>%s (rate %.2f)</td></tr>\n",
            sim_fec_string(config->system.fec_type), config->system.code_rate);
    fprintf(fp, "<tr><td>Packets</td><td>%d × %d bytes</td></tr>\n",
            config->control.num_packets, config->control.packet_size);
    fprintf(fp, "</table>\n\n");
    
    // Results section
    fprintf(fp, "<h2>Results Summary</h2>\n");
    fprintf(fp, "<table>\n");
    fprintf(fp, "<tr><th>Metric</th><th>Value</th></tr>\n");
    fprintf(fp, "<tr><td>Average BER</td><td class='metric'>%.3e</td></tr>\n",
            results->avg_ber);
    fprintf(fp, "<tr><td>Average SNR</td><td class='metric'>%.2f dB</td></tr>\n",
            results->avg_snr);
    fprintf(fp, "<tr><td>Packet Loss Rate</td><td class='metric'>%.3f%% (%.3e)</td></tr>\n",
            results->packet_loss_rate * 100.0, results->packet_loss_rate);
    fprintf(fp, "<tr><td>Average Throughput</td><td class='metric'>%.3e bits/s</td></tr>\n",
            results->avg_throughput);
    fprintf(fp, "<tr><td>Total Bits</td><td>%lld</td></tr>\n", results->total_bits);
    fprintf(fp, "<tr><td>Total Bit Errors</td><td>%lld</td></tr>\n", results->total_bit_errors);
    fprintf(fp, "<tr><td>FEC Corrected Errors</td><td>%lld</td></tr>\n",
            results->fec_corrected_errors);
    fprintf(fp, "</table>\n\n");
    
    // Tracking results if enabled
    if (results->tracking_enabled) {
        fprintf(fp, "<h2>Beam Tracking</h2>\n");
        fprintf(fp, "<table>\n");
        fprintf(fp, "<tr><th>Metric</th><th>Value</th></tr>\n");
        fprintf(fp, "<tr><td>Tracking Updates</td><td>%d</td></tr>\n",
                results->tracking_updates);
        fprintf(fp, "<tr><td>Reacquisitions</td><td>%d</td></tr>\n",
                results->reacquisitions);
        fprintf(fp, "<tr><td>Average Azimuth</td><td>%.3f rad (%.2f deg)</td></tr>\n",
                results->avg_beam_azimuth, results->avg_beam_azimuth * 180.0 / FSO_PI);
        fprintf(fp, "<tr><td>Average Elevation</td><td>%.3f rad (%.2f deg)</td></tr>\n",
                results->avg_beam_elevation, results->avg_beam_elevation * 180.0 / FSO_PI);
        fprintf(fp, "</table>\n\n");
    }
    
    // Footer
    fprintf(fp, "<hr>\n");
    fprintf(fp, "<p><small>Simulation Duration: %.3f seconds</small></p>\n",
            results->simulation_duration);
    
    fprintf(fp, "</body>\n</html>\n");
    
    fclose(fp);
    
    FSO_LOG_INFO("Visualization", "Generated HTML report: %s", output_filename);
    return FSO_SUCCESS;
}

/**
 * @brief Generate all visualization outputs for a simulation
 * 
 * Convenience function that generates all plots and reports.
 * 
 * @param config Simulation configuration
 * @param results Simulation results
 * @param base_filename Base filename for outputs (without extension)
 * @return FSO_SUCCESS on success, error code otherwise
 */
int sim_generate_all_visualizations(const SimConfig* config,
                                    const SimResults* results,
                                    const char* base_filename) {
    if (config == NULL || results == NULL || base_filename == NULL) {
        FSO_LOG_ERROR("Visualization", "NULL pointer in generate_all_visualizations");
        return FSO_ERROR_INVALID_PARAM;
    }
    
    char filename[256];
    int result;
    
    // Export CSV files
    snprintf(filename, sizeof(filename), "%s_timeseries.csv", base_filename);
    result = sim_results_export_csv(results, filename);
    if (result != FSO_SUCCESS) {
        FSO_LOG_ERROR("Visualization", "Failed to export time-series CSV");
        return result;
    }
    
    snprintf(filename, sizeof(filename), "%s_packets.csv", base_filename);
    result = sim_results_export_packets_csv(results, filename);
    if (result != FSO_SUCCESS) {
        FSO_LOG_ERROR("Visualization", "Failed to export packets CSV");
        return result;
    }
    
    // Generate gnuplot scripts
    char csv_file[256], png_file[256], script_file[256];
    
    // Time-series plot
    snprintf(csv_file, sizeof(csv_file), "%s_timeseries.csv", base_filename);
    snprintf(png_file, sizeof(png_file), "%s_timeseries.png", base_filename);
    snprintf(script_file, sizeof(script_file), "%s_timeseries.gp", base_filename);
    sim_generate_timeseries_plot(csv_file, png_file, script_file);
    
    // BER vs SNR plot
    snprintf(csv_file, sizeof(csv_file), "%s_packets.csv", base_filename);
    snprintf(png_file, sizeof(png_file), "%s_ber_snr.png", base_filename);
    snprintf(script_file, sizeof(script_file), "%s_ber_snr.gp", base_filename);
    sim_generate_ber_snr_plot(csv_file, png_file, script_file);
    
    // Tracking plot if enabled
    if (results->tracking_enabled) {
        snprintf(csv_file, sizeof(csv_file), "%s_timeseries.csv", base_filename);
        snprintf(png_file, sizeof(png_file), "%s_tracking.png", base_filename);
        snprintf(script_file, sizeof(script_file), "%s_tracking.gp", base_filename);
        sim_generate_tracking_plot(csv_file, png_file, script_file);
    }
    
    // Generate HTML report
    snprintf(filename, sizeof(filename), "%s_report.html", base_filename);
    result = sim_generate_html_report(config, results, filename);
    if (result != FSO_SUCCESS) {
        FSO_LOG_ERROR("Visualization", "Failed to generate HTML report");
        return result;
    }
    
    FSO_LOG_INFO("Visualization", "Generated all visualizations with base: %s", base_filename);
    
    printf("\nGenerated files:\n");
    printf("  - %s_timeseries.csv (time-series data)\n", base_filename);
    printf("  - %s_packets.csv (packet statistics)\n", base_filename);
    printf("  - %s_timeseries.gp (gnuplot script)\n", base_filename);
    printf("  - %s_ber_snr.gp (gnuplot script)\n", base_filename);
    if (results->tracking_enabled) {
        printf("  - %s_tracking.gp (gnuplot script)\n", base_filename);
    }
    printf("  - %s_report.html (HTML report)\n", base_filename);
    printf("\nTo generate plots, run:\n");
    printf("  gnuplot %s_timeseries.gp\n", base_filename);
    printf("  gnuplot %s_ber_snr.gp\n", base_filename);
    if (results->tracking_enabled) {
        printf("  gnuplot %s_tracking.gp\n", base_filename);
    }
    printf("\n");
    
    return FSO_SUCCESS;
}
